//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCSINH
    {
        public HOCSINH()
        {
            this.CHITIETDANHGIAs = new HashSet<CHITIETDANHGIA>();
        }
    
        public string HS_MA { get; set; }
        public string HS_HOTEN { get; set; }
        public string HS_GIOITINH { get; set; }
        public System.DateTime HS_NGAYSINH { get; set; }
        public string HS_TONGIAO { get; set; }
        public string TINHTHANH_TT_MA { get; set; }
        public string XAPHUONG_XP_MA { get; set; }
        public string KYLUAT_KL_MA { get; set; }
        public string KHENTHUONG_KT_MA { get; set; }
        public string QUANHUYEN_QH_MA { get; set; }
        public string DANTOC_DT_MA { get; set; }
        public string LOP_LOP_MA { get; set; }
        public string KHOI_KHOI_MA { get; set; }
    
        public virtual ICollection<CHITIETDANHGIA> CHITIETDANHGIAs { get; set; }
        public virtual DANTOC DANTOC { get; set; }
        public virtual KHENTHUONG KHENTHUONG { get; set; }
        public virtual KHOI KHOI { get; set; }
        public virtual KYLUAT KYLUAT { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual QUANHUYEN QUANHUYEN { get; set; }
        public virtual TINHTHANH TINHTHANH { get; set; }
        public virtual XAPHUONG XAPHUONG { get; set; }
    }
}
