//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHENTHUONGCB
    {
        public KHENTHUONGCB()
        {
            this.CANBOes = new HashSet<CANBO>();
        }
    
        public string KTCB_MA { get; set; }
        public string KTCB_NGAY { get; set; }
        public string KTCB_THANHTICH { get; set; }
    
        public virtual ICollection<CANBO> CANBOes { get; set; }
    }
}
