//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class acomptec_qlthptEntities : DbContext
    {
        public acomptec_qlthptEntities()
            : base("name=acomptec_qlthptEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BACLUONG> BACLUONGs { get; set; }
        public DbSet<CANBO> CANBOes { get; set; }
        public DbSet<CHITIET_CHUCVU> CHITIET_CHUCVU { get; set; }
        public DbSet<CHITIETDANHGIA> CHITIETDANHGIAs { get; set; }
        public DbSet<CHUCVU> CHUCVUs { get; set; }
        public DbSet<CHUYENNGANH> CHUYENNGANHs { get; set; }
        public DbSet<COQUAN> COQUANs { get; set; }
        public DbSet<COSOVATCHAT> COSOVATCHATs { get; set; }
        public DbSet<DANTOC> DANTOCs { get; set; }
        public DbSet<HINHTHUC> HINHTHUCs { get; set; }
        public DbSet<HOCKY> HOCKies { get; set; }
        public DbSet<HOCSINH> HOCSINHs { get; set; }
        public DbSet<KHENTHUONG> KHENTHUONGs { get; set; }
        public DbSet<KHENTHUONGCB> KHENTHUONGCBs { get; set; }
        public DbSet<KHOI> KHOIs { get; set; }
        public DbSet<KYLUAT> KYLUATs { get; set; }
        public DbSet<KYLUATCB> KYLUATCBs { get; set; }
        public DbSet<LOP> LOPs { get; set; }
        public DbSet<MONHOC> MONHOCs { get; set; }
        public DbSet<NAMHOC> NAMHOCs { get; set; }
        public DbSet<NGACHLUONG> NGACHLUONGs { get; set; }
        public DbSet<PHONGHOC> PHONGHOCs { get; set; }
        public DbSet<QUANHUYEN> QUANHUYENs { get; set; }
        public DbSet<SODANHGIA> SODANHGIAs { get; set; }
        public DbSet<THIETBIDAYHOC> THIETBIDAYHOCs { get; set; }
        public DbSet<THIETBIGIANGDAY> THIETBIGIANGDAYs { get; set; }
        public DbSet<THOIKHOABIEU> THOIKHOABIEUx { get; set; }
        public DbSet<THONGTINDAOTAO> THONGTINDAOTAOs { get; set; }
        public DbSet<THONGTINLUONG> THONGTINLUONGs { get; set; }
        public DbSet<THU> THUs { get; set; }
        public DbSet<TIETHOC> TIETHOCs { get; set; }
        public DbSet<TINHTHANH> TINHTHANHs { get; set; }
        public DbSet<TINHTRANG> TINHTRANGs { get; set; }
        public DbSet<UpdateImage> UpdateImages { get; set; }
        public DbSet<VANBANG> VANBANGs { get; set; }
        public DbSet<XAPHUONG> XAPHUONGs { get; set; }
    }
}
