//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SODANHGIA
    {
        public SODANHGIA()
        {
            this.CHITIETDANHGIAs = new HashSet<CHITIETDANHGIA>();
        }
    
        public string SDG_MA { get; set; }
        public string SDG_DIEM { get; set; }
        public string SDG_GHICHU { get; set; }
        public string NAMHOC_NH_MA { get; set; }
    
        public virtual ICollection<CHITIETDANHGIA> CHITIETDANHGIAs { get; set; }
        public virtual NAMHOC NAMHOC { get; set; }
    }
}
