//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THOIKHOABIEU
    {
        public string TKB_MA { get; set; }
        public string LOP_LOP_MA { get; set; }
        public string MONHOC_MH_MA { get; set; }
        public string THU_THU_MA { get; set; }
        public string TIETHOC_TH_MA { get; set; }
        public string CANBO_CB_MA { get; set; }
        public string HOCKY_HK_MA { get; set; }
    
        public virtual CANBO CANBO { get; set; }
        public virtual HOCKY HOCKY { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        public virtual THU THU { get; set; }
        public virtual TIETHOC TIETHOC { get; set; }
    }
}
