//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINLUONG
    {
        public string TTL_MA { get; set; }
        public string TTL_NGAYNHANLUONG { get; set; }
        public string TTL_HESOLUONG { get; set; }
        public string BACLUONG_BL_MA { get; set; }
        public string NGACHLUONG_NL_MA { get; set; }
        public string CANBO_CB_MA { get; set; }
    
        public virtual BACLUONG BACLUONG { get; set; }
        public virtual CANBO CANBO { get; set; }
        public virtual NGACHLUONG NGACHLUONG { get; set; }
    }
}
